spring.application.name=demo

# H2
spring.datasource.url=jdbc:h2:mem:boarddb
spring.datasource.driverClassName=org.h2.driver
spring.datasource.username=behindy
spring.datasource.password=my_little_password

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA Config

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# File Upload Config
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
file.upload.directory=uploads

# ???
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
spring.thymeleaf.encoding=UTF-8

# ??
logging.level.com.example.board=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n